// Generated by CoffeeScript 1.3.3
(function() {
  var ImageDropper, init;

  init = function() {
    var dropper;
    dropper = new ImageDropper($('.drop-target'));
    return dropper.onImageDropped = function(img) {
      return console.log(img);
    };
  };

  ImageDropper = (function() {

    function ImageDropper(target) {
      var _this = this;
      target = $(target);
      target.bind('dragover', function(event) {
        event.stopPropagation();
        event.preventDefault();
        return target.addClass('dragover');
      }).bind('dragout', function(event) {
        event.stopPropagation();
        event.preventDefault();
        return target.removeClass('dragover');
      }).bind('drop', function(event) {
        event.stopPropagation();
        event.preventDefault();
        target.removeClass('dragover');
        return _this.getImage(event.originalEvent.dataTransfer.files);
      });
    }

    ImageDropper.prototype.getImage = function(files) {
      var reader,
        _this = this;
      reader = new FileReader;
      reader.onload = function(event) {
        var img;
        img = new Image;
        img.src = event.target.result;
        return img.onload = function() {
          if (_this.onImageDropped != null) {
            return _this.onImageDropped(img);
          }
        };
      };
      return reader.readAsDataURL(files[0]);
    };

    return ImageDropper;

  })();

  init();

}).call(this);
